#!/bin/bash
# AdaptLight Raspberry Pi Setup Script
# Run this after copying the raspi folder to your Raspberry Pi 5
#
# Usage: cd /path/to/raspi && ./setup.sh

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}   AdaptLight Raspberry Pi Setup       ${NC}"
echo -e "${GREEN}========================================${NC}"

# Get the directory where this script is located (raspi folder)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RASPI_DIR="$SCRIPT_DIR"

# Create venv folder one level up from raspi folder
PARENT_DIR="$(dirname "$RASPI_DIR")"
VENV_DIR="$PARENT_DIR/adaptlight_venv"

echo -e "\n${YELLOW}Configuration:${NC}"
echo "  Raspi folder: $RASPI_DIR"
echo "  Venv folder:  $VENV_DIR"

# Step 1: Install system dependencies
echo -e "\n${GREEN}[1/5] Installing system dependencies...${NC}"
sudo apt-get update
sudo apt-get install -y \
    python3-pip \
    python3-venv \
    python3-dev \
    portaudio19-dev \
    libffi-dev \
    libssl-dev \
    libasound2-dev \
    libopenblas-dev \
    swig \
    liblgpio-dev

# Try to install libatlas-base-dev (may not exist on newer Debian)
sudo apt-get install -y libatlas-base-dev 2>/dev/null || echo "libatlas-base-dev not available, skipping (libopenblas-dev provides equivalent functionality)"

# Step 2: Create virtual environment outside raspi folder
echo -e "\n${GREEN}[2/5] Creating virtual environment at $VENV_DIR...${NC}"
if [ -d "$VENV_DIR" ]; then
    echo -e "${YELLOW}Virtual environment already exists. Removing and recreating...${NC}"
    rm -rf "$VENV_DIR"
fi
python3 -m venv "$VENV_DIR"

# Step 3: Activate venv and install requirements
echo -e "\n${GREEN}[3/5] Installing Python dependencies...${NC}"
source "$VENV_DIR/bin/activate"

# Upgrade pip first
pip install --upgrade pip wheel setuptools

# Install requirements
pip install -r "$RASPI_DIR/requirements.txt"

deactivate

# Step 4: Create the startup script
echo -e "\n${GREEN}[4/5] Creating startup script...${NC}"
STARTUP_SCRIPT="$PARENT_DIR/start_adaptlight.sh"

cat > "$STARTUP_SCRIPT" << EOF
#!/bin/bash
# AdaptLight Startup Script
# Auto-generated by setup.sh

# Activate virtual environment
source "$VENV_DIR/bin/activate"

# Change to raspi directory
cd "$RASPI_DIR"

# Run main.py
python main.py "\$@"
EOF

chmod +x "$STARTUP_SCRIPT"
echo "  Created: $STARTUP_SCRIPT"

# Step 5: Create and enable systemd service for auto-startup
echo -e "\n${GREEN}[5/5] Setting up auto-startup service...${NC}"

SERVICE_FILE="/etc/systemd/system/adaptlight.service"

sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=AdaptLight LED Controller
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$RASPI_DIR
ExecStart=$VENV_DIR/bin/python $RASPI_DIR/main.py
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

# Environment variables (if needed)
Environment="HOME=$HOME"
Environment="PATH=$VENV_DIR/bin:/usr/local/bin:/usr/bin:/bin"

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd and enable the service
sudo systemctl daemon-reload
sudo systemctl enable adaptlight.service

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}   Setup Complete!                     ${NC}"
echo -e "${GREEN}========================================${NC}"

echo -e "\n${YELLOW}Summary:${NC}"
echo "  Virtual environment: $VENV_DIR"
echo "  Startup script:      $STARTUP_SCRIPT"
echo "  Systemd service:     adaptlight.service"

echo -e "\n${YELLOW}Useful commands:${NC}"
echo "  Start manually:      $STARTUP_SCRIPT"
echo "  Start service:       sudo systemctl start adaptlight"
echo "  Stop service:        sudo systemctl stop adaptlight"
echo "  View logs:           sudo journalctl -u adaptlight -f"
echo "  Disable auto-start:  sudo systemctl disable adaptlight"

echo -e "\n${YELLOW}Configuration:${NC}"
echo "  Edit $RASPI_DIR/config.yaml before running"
echo "  Copy from config.example.yaml if needed"

echo -e "\n${GREEN}The service will start automatically on next boot.${NC}"
echo -e "${GREEN}To start now: sudo systemctl start adaptlight${NC}"
